### ISSUE TITLE
Bundled EVIO too old

### ISSUE THREAD

**Issue by hansenjo** [JeffersonLab/japan-MOLLER#7]
The included evio package, lifted from the Hall A analyzer, is very old (v1). EVIO is now at least at v5, with v6 underway. Maybe we should make EVIO an external dependency that auto-downloads itself if not found, like Podd does?

**Comment by paulmking** [comment]
Ryan has started work on this.

**Comment by paulmking** [comment]
This should now be resolved after PR #20
